### ISSUE TITLE
Token type hint is required for some provider

### ISSUE THREAD

**Issue by dbaje** [mubashiroliyantakath/toi#4]
Hello, I am currently using casdoor. The introspect endpoint requires a parameter/form field for "token_type_hint"

https://demo.casdoor.com/swagger/#/Login%20API/ApiController.IntrospectToken

Would it be possible to add a configuration where we can set a value optionally that will set the "token_type_hint" if present?

**Comment by mubashiroliyantakath** [comment]
Happy to look into this.
